import type { CurrentWeather, ForecastDay, AirQuality } from './types'

export const mockAirQuality: AirQuality = {
  aqi: 42,
  level: 'Good',
  pm25: 8.2,
  pm10: 18.5,
  o3: 65.0,
  no2: 12.4,
}

export const mockCurrentWeather: CurrentWeather = {
  city: 'Kigali',
  country: 'Rwanda',
  temperature: 22,
  feelsLike: 23,
  condition: 'partly-cloudy',
  description: 'Partly cloudy with mild breeze',
  humidity: 68,
  dewPoint: 15,
  windSpeed: 14,
  windDirection: 'SW',
  visibility: 12,
  uvIndex: 7,
  pressure: 1013,
  precipitation: 0.0,
  sunrise: '05:48',
  sunset: '17:52',
  high: 25,
  low: 15,
  lastUpdated: 'Just now',
  airQuality: mockAirQuality,
}

export const mockForecast: ForecastDay[] = [
  {
    date: 'Tomorrow',
    dayName: 'Thu',
    condition: 'rainy',
    description: 'Light showers',
    high: 21,
    low: 14,
    humidity: 82,
    windSpeed: 18,
    chanceOfRain: 75,
  },
  {
    date: 'Fri, Mar 7',
    dayName: 'Fri',
    condition: 'cloudy',
    description: 'Overcast',
    high: 20,
    low: 15,
    humidity: 74,
    windSpeed: 12,
    chanceOfRain: 30,
  },
  {
    date: 'Sat, Mar 8',
    dayName: 'Sat',
    condition: 'partly-cloudy',
    description: 'Partly cloudy',
    high: 24,
    low: 16,
    humidity: 62,
    windSpeed: 10,
    chanceOfRain: 15,
  },
  {
    date: 'Sun, Mar 9',
    dayName: 'Sun',
    condition: 'sunny',
    description: 'Mostly sunny',
    high: 27,
    low: 16,
    humidity: 55,
    windSpeed: 8,
    chanceOfRain: 5,
  },
  {
    date: 'Mon, Mar 10',
    dayName: 'Mon',
    condition: 'stormy',
    description: 'Thunderstorms',
    high: 19,
    low: 13,
    humidity: 90,
    windSpeed: 28,
    chanceOfRain: 90,
  },
]

export const cityDatabase: { city: string; country: string }[] = [
  { city: 'Kigali', country: 'Rwanda' },
  { city: 'Butare', country: 'Rwanda' },
  { city: 'Gisenyi', country: 'Rwanda' },
  { city: 'Ruhengeri', country: 'Rwanda' },
  { city: 'Nairobi', country: 'Kenya' },
  { city: 'Lagos', country: 'Nigeria' },
  { city: 'Accra', country: 'Ghana' },
  { city: 'Kampala', country: 'Uganda' },
  { city: 'Dar es Salaam', country: 'Tanzania' },
  { city: 'Addis Ababa', country: 'Ethiopia' },
  { city: 'London', country: 'United Kingdom' },
  { city: 'Paris', country: 'France' },
  { city: 'New York', country: 'USA' },
  { city: 'Tokyo', country: 'Japan' },
  { city: 'Dubai', country: 'UAE' },
]
